apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: waterdrips-gadmintoken
  namespace: openfaas-fn
spec:
  encryptedData:
    gadmin-token: AgAG8PdeaPvpJkfzg2qR+rBtanQU94bsPgMhhe129w8tlO6vwlfduVOrSe7F10cTTaKMefq0wej5Pa6TbHbveMosMDY1LUA9ofDCUN9YrmFIBTyYhDRjuxkqbRn8EOR6cEWdi58Yh5mejzLQ+XyadH5Ucv9gFwkBNV6Z6Xedu6HJkInrucWWgvvzUf0qjve7lp1DbuPWjnEUzgDq3xDw2pAjSK6rRlJrH3W7RCxXhXyUo0HEJwSC8S+66o/FiCYfTO0lGQRR2DhhyOPVYq100OVVf1H3sA0TqBTtiPRmx5+xjees4KaoFROVV+4vEZnZ//hw4gA4L8ADNHuFdyCZ9/JSCawJhSQzgZ9rWzHwb84ATir7tG1dEuoHBIqfcdQQHfi0hvHxiCc+3H0+1fuBJj9nuG9JeWrmzW33NTgx7L+6JD4EZJ9yCsolXnOLVir2RdoZ+LEXbwiprUUpRLBHsolLXUnRkVngzQP1OQ1JOPqM7yOeVSxi2HMsHk2ine+RE6em6tYoUnuaZg/FWVrqk9kh7oJh7aCujfWhf4S3hDYp7r2pQo3q/4HdXuXrXzxfqBTd+iKmnMeTRY7Y/+/ElVcJ8oqKrSan2/saTfEVKwnVue9GWUANozuVbXN3xwqxG+sUp5w1PMkb/Va/A6fqtNRopVgLTCNVm+Cp//WZcdITVl2vNZk+PG8VDAoZoKSz1eh8qJno064=
  template:
    metadata:
      creationTimestamp: null
      name: waterdrips-gadmintoken
      namespace: openfaas-fn

