version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  add-post:
    lang: golang-middleware
    handler: ./add-post
    image: add-post:0.1.0
    environment:
      GITHUB_REPO: https://github.com/Waterdrips/kubecon-blog
      content_type: "text/plain"
    build_args:
      GO111MODULE: on
    secrets:
      - github-token
  blog:
    lang: hugo
    handler: ./blog
    image: blog:latest
